# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_game_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
